# Generated by Django 4.2.10 on 2024-03-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review_or_comment',
            old_name='recipe',
            new_name='recipe_id',
        ),
        migrations.AlterField(
            model_name='review_or_comment',
            name='review',
            field=models.TextField(),
        ),
    ]
